from enum import Enum


class PymodelioSetting(Enum):
    INIT_PROTECTED_ATTRS_BY_DEFAULT = 'INIT_PROTECTED_ATTRS_BY_DEFAULT'
    INIT_PRIVATE_ATTRS_BY_DEFAULT = 'INIT_PRIVATE_ATTRS_BY_DEFAULT'
    USE_CACHE_OPTIMIZATIONS = 'USE_CACHE_OPTIMIZATIONS'
    AUTO_PARSE_DATES_AS_UTC = 'AUTO_PARSE_DATES_AS_UTC'
    USE_DEFAULT_ATTR_VALIDATOR_IF_NOT_DEFINED = 'USE_DEFAULT_ATTR_VALIDATOR_IF_NOT_DEFINED'
