from enum import Enum


class PymodelioSetting(Enum):
    AUTO_PARSE_DATES_AS_UTC = 'AUTO_PARSE_DATES_AS_UTC'
    USE_DEFAULT_ATTR_VALIDATOR_IF_NOT_DEFINED = 'USE_DEFAULT_ATTR_VALIDATOR_IF_NOT_DEFINED'
